version: '3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/prd/mysql
    env_file:
      - ./.env

  app:
    build: .
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./prisma:/usr/src/app/prisma
    restart: always

volumes:
  db_data:
