version: '3.8'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    env_file: ./.env

  app:
    build: 
      context: ../
      dockerfile: ./Dockerfile.dev
    ports:
      - "3000:3000"
    depends_on: 
      - db
    restart: always
    volumes:
      - ../:/usr/src/app

volumes:
  db_data:
