version: '3.8'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dentalwelt_password
      MYSQL_DATABASE: dentalwelt_db
      MYSQL_USER: dentalwelt_user
      MYSQL_PASSWORD: '123456'
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - ./.env

  app:
    build: 
      context: ../
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    depends_on: 
      - db
    env_file:
      - ./.env  
    restart: always
    volumes:
      - ../:/app
      - /app/node_modules

volumes:
  db_data: