version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: databasedw
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: 
      context: ../
      dockerfile: ./Dockerfile.dev
    ports:
      - "3000:3000"
    depends_on: 
      - db
    restart: always
    volumes:
      - ../:/usr/src/app

volumes:
  db_data: